PLMWebApp/Areas/Admin/Controllers/UserlistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PLM.DataAccess;
using PLM.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting;
using PLM.Models;
using PLM.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using PLM.Utility;

namespace PLMWebApp.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Logistics + "," + SD.Role_Sales)]
public class UserlistController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;

    public UserlistController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public IActionResult Index()
    {
        return View();
    }

    //GET
    public IActionResult Update(string email)
    {
        UserVM user = new();
        user.applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Email == email);
        user.RolesList = _roleManager.Roles.Select(x => x.Name).Select(i => new SelectListItem
        {
            Text = i,
            Value = i
        });
        return View(user);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(UserVM userVM)
    {
        //if (ModelState.IsValid)
        //{
        ApplicationUser user = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Email == userVM.applicationUser.Email);

        if (user.RoleName != userVM.applicationUser.RoleName)
        {
            var realuser = _userManager.FindByIdAsync(user.Id).Result;
            await _userManager.RemoveFromRoleAsync(realuser, user.RoleName);
            await _userManager.AddToRoleAsync(realuser, userVM.applicationUser.RoleName);
            user.RoleName = userVM.applicationUser.RoleName;
        }
        if (userVM.applicationUser.Warnings == 1)
        {
            user.Warnings = 1;
            user.Warning1 = userVM.applicationUser.Warning1;
            user.Warning2 = "";
        }
        else if (userVM.applicationUser.Warnings == 2)
        {
            user.Warnings = 2;
            user.Warning1 = userVM.applicationUser.Warning1;
            user.Warning2 = userVM.applicationUser.Warning2;
        }
        else
        {
            user.Warnings = 0;
            user.Warning1 = "";
            user.Warning2 = "";
        }
        _unitOfWork.Save();

        return RedirectToAction("Index");
        //}
        //return View(userVM);
    }

    //GET
    //public IActionResult Delete(int? id)
    //{
    //    if (id == null || id == 0)
    //    {
    //        return NotFound();
    //    }

    //    var productFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

    //    if (productFromDbFirst == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(productFromDbFirst);
    //}



    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var userList = _unitOfWork.ApplicationUser.GetAll();
        return Json(new { data = userList });
    }

    ////POST
    //[HttpDelete]
    //public IActionResult Delete(int? id)
    //{
    //    var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
    //    if (obj == null)
    //    {
    //        return Json(new { success = false, message = "Error while deactivating" });
    //    }

    //    //var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
    //    //if (System.IO.File.Exists(oldImagePath))
    //    //{
    //    //    System.IO.File.Delete(oldImagePath);
    //    //}
    //    obj.IsActive = false;
    //    obj.Inactivity = DateTime.Now;
    //    _unitOfWork.Product.Update(obj);
    //    _unitOfWork.Save();
    //    return Json(new { success = true, message = "Product Deactivated Successfully" });
    //    //return RedirectToAction("Index");

    //}

    //public IActionResult Activate(int? id)
    //{
    //    var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
    //    if (obj == null)
    //    {
    //        return Json(new { success = false, message = "Error while Reactivating" });
    //    }

    //    //var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
    //    //if (System.IO.File.Exists(oldImagePath))
    //    //{
    //    //    System.IO.File.Delete(oldImagePath);
    //    //}
    //    obj.IsActive = true;
    //    _unitOfWork.Product.Update(obj);
    //    _unitOfWork.Save();
    //    return Json(new { success = true, message = "Product Reactivated Successfully" });
    //    //return RedirectToAction("Index");

    //}

    #endregion
}

PLMWebApp/Areas/Admin/Views/Userlist/Index.cshtml
@{
    ViewData["Title"] = "All Users";
}

<div class="container p-3">

    <div class="row pt-4"> 
        <div class="col-6">
            <h2 class="text-primary">All Users</h2>
        </div>
        <div class="col-6 text-end">
        </div>
    </div>

    <br /> 

    <table id="tblData" class="table table-hover" style="width: 100%" > 
        <thead>
            <tr>
                <th>
                    Email
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Phone
                </th>
                <th>
                    Role
                </th>
                <th>
                    Warnings
                </th>
                <th></th>
            </tr>
        </thead>
    </table>

</div>


@section Scripts{
    <script src="~/js/user.js"></script>
}

PLMWebApp/Areas/Admin/Views/Userlist/Update.cshtml
@using PLM.Utility
@model PLM.Models.ViewModels.UserVM

@{
    ViewData["Title"] = @Model.applicationUser.FirstName +" "+@Model.applicationUser.LastName;
}

<form method="post" asp-action="Update" enctype="multipart/form-data">
    <input asp-for="applicationUser.Id" hidden />
    <input asp-for="applicationUser.FirstName" hidden />
    <input asp-for="applicationUser.LastName" hidden />
    <input asp-for="applicationUser.Email" hidden />

    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">Update User @Model.applicationUser.Email</h2>
                </div>
                <div class="mb-3">
                    @*<div asp-validation-summary="All"></div>*@
                    <label asp-for="applicationUser.Warnings"></label>
                    <br />
                    <input asp-for="applicationUser.Warnings" type="number" class="form-control" id="warning" placeholder="Warnings">
                    <span asp-validation-for="applicationUser.Warnings" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    @*<div asp-validation-summary="All"></div>*@
                    <label>Warning Reason 1:</label>
                    <br />
                    <input asp-for="applicationUser.Warning1" type="text" class="form-control" id="warn1">
                    <span asp-validation-for="applicationUser.Warning1" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    @*<div asp-validation-summary="All"></div>*@
                    <label>Warning Reason 2:</label>
                    <br />
                    <input asp-for="applicationUser.Warning2" type="text" class="form-control" id="warn2">
                    <span asp-validation-for="applicationUser.Warnings" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    @*<div asp-validation-summary="All"></div>*@
                    @if (User.IsInRole(SD.Role_Admin))
                    {
                        <label>User's Role</label>
                        <br />
                        <select asp-for="applicationUser.RoleName" asp-items="@Model.RolesList" class="form-select">
                        </select>
                    } else
                    {
                        <select asp-for="applicationUser.RoleName" asp-items="@Model.RolesList" class="form-select" hidden>
                        </select>
                    }
                    <span asp-validation-for="applicationUser.RoleName" class="text-danger"></span>
                
                </div>
                <div class="col-12">
                        <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width: 150px">Update</button>
                            <a asp-controller="Userlist" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back To List</a>
                </div>
            </div>
        </div>
    </div>


</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
    <script>
        //tinymce.init({
        //    selector: 'textarea',
        //    plugins: 'a11ychecker advcode casechange export formatpainter image editimage linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tableofcontents tinycomments tinymcespellchecker',
        //    toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter image editimage pageembed permanentpen table tableofcontents',
        //    toolbar_mode: 'floating',
        //    tinycomments_mode: 'embedded',
        //    tinycomments_author: 'Author name',
        //});

        function ValidateInput(){
            var a = document.getElementById("warning").value;
            var b = document.getElementById("warn1").value;
            var c = document.getElementById("warn2").value;

            if (a == 1 && b == "") 
            {
                Swal.fire
                    ({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Add a reason for warning'
                    });
                return false;
            }
            if (a == 2 && (b == ""|| c == "")) 
            {
                Swal.fire
                    ({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Add a reason for warning'
                    });
                return false;
            }
            return true;
        }
    </script>
}