PLMWebApp/Areas/Admin/Controllers/InventoryReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PLM.DataAccess;
using PLM.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting;
using PLM.Models;
using PLM.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using PLM.Utility;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity.UI.Services;
using OfficeOpenXml;

namespace PLMWebApp.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Operation + "," + SD.Role_Logistics + "," + SD.Role_Sales)]
public class InventoryReportController : Controller
{
    private readonly IEmailSender _emailSender;
    private readonly IUnitOfWork _unitOfWork;
    private readonly UserManager<IdentityUser> _userManager;

    public InventoryReportController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, IEmailSender emailSender)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _emailSender = emailSender;
    }


    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Products(int id)
    {
        InventoryReport Report = _unitOfWork.InventoryReport.GetFirstOrDefault(u => u.Id == id);
        return View(Report);
    }

    public IActionResult Batches(int id, int pid)
    {
        InvReportDetail Product = _unitOfWork.InvReportDetail.GetFirstOrDefault(u => u.ReportId == id && u.ProductId == pid);
        return View(Product);
    }

    public bool ValidateRole(string email, string role)
    {
        var user = _userManager.FindByEmailAsync(email).Result;
        return _userManager.IsInRoleAsync(user, role).Result;
    }
    //GET
    public IActionResult Upsert(int? id)
    {
        InventoryReport Inventory = new();

        if (id == null || id == 0)
        {
            //create
            return View(Inventory);
        }
        else
        {
            //update
            Inventory = _unitOfWork.InventoryReport.GetFirstOrDefault(u => u.Id == id);
            return View(Inventory);
        }

    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(InventoryReport Inventory)
    {
        if (ModelState.IsValid)
        {
            if (Inventory.Id == 0)
            {
                DateTime today = DateTime.Now;
                Inventory.GenerationDate = new DateTime(today.Year, today.Month, today.Day, today.Hour, today.Minute, today.Second, today.Kind);
                _unitOfWork.InventoryReport.Add(Inventory);
                _unitOfWork.Save();
                IEnumerable<Product> products = _unitOfWork.Product.GetAll(u => u.IsActive, includeProperties: "Brand,Category");
                foreach (Product product in products)
                {
                    InvReportDetail detail = new InvReportDetail()
                    {
                        ReportId = Inventory.Id,
                        DetailType = "Product",
                        ProductBrand = product.Brand.Name,
                        ProductCategory = product.Category.Name,
                        ProductName = product.Name,
                        ProductId = product.Id,
                        ProductPrice = product.Price,
                        ProductExpiry = product.Expiry,
                        ProductStatus = product.StockStat,
                        ProductStock = product.Stock,
                        BatchBase = 0,
                        BatchExpiry = new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Unspecified),
                        BatchId = 0,
                        BatchStock = 0,
                    };
                    _unitOfWork.InvReportDetail.Add(detail);
                    IEnumerable<Batch> batches = _unitOfWork.Batch.GetAll(u => u.ProductId == product.Id && u.Stock > 0);
                    foreach (Batch batch in batches)
                    {
                        InvReportDetail Bdetail = new InvReportDetail()
                        {
                            ReportId = Inventory.Id,
                            DetailType = "Batch",
                            ProductBrand = product.Brand.Name,
                            ProductCategory = product.Category.Name,
                            ProductName = product.Name,
                            ProductId = product.Id,
                            ProductPrice = product.Price,
                            ProductExpiry = product.Expiry,
                            ProductStatus = product.StockStat,
                            ProductStock = product.Stock,
                            BatchBase = batch.BasePrice,
                            BatchExpiry = batch.Expiry,
                            BatchId = batch.Id,
                            BatchStock = batch.Stock
                        };
                        _unitOfWork.InvReportDetail.Add(Bdetail);
                    };
                }
                TempData["Success"] = "Report Generated Successfully";
            }
            else
            {
                _unitOfWork.InvReportDetail.RemoveRange(_unitOfWork.InvReportDetail.GetAll(u => u.ReportId == Inventory.Id));
                IEnumerable<Product> products = _unitOfWork.Product.GetAll(u => u.IsActive, includeProperties: "Brand,Category");
                foreach (Product product in products)
                {
                    InvReportDetail detail = new InvReportDetail()
                    {
                        ReportId = Inventory.Id,
                        DetailType = "Product",
                        ProductBrand = product.Brand.Name,
                        ProductCategory = product.Category.Name,
                        ProductName = product.Name,
                        ProductId = product.Id,
                        ProductPrice = product.Price,
                        ProductExpiry = product.Expiry,
                        ProductStatus = product.StockStat,
                        ProductStock = product.Stock,
                        BatchBase = 0,
                        BatchExpiry = new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Unspecified),
                        BatchId = 0,
                        BatchStock = 0
                    };
                    _unitOfWork.InvReportDetail.Add(detail);
                    IEnumerable<Batch> batches = _unitOfWork.Batch.GetAll(u => u.ProductId == product.Id && u.Stock > 0);
                    foreach (Batch batch in batches)
                    {
                        InvReportDetail Bdetail = new InvReportDetail()
                        {
                            ReportId = Inventory.Id,
                            DetailType = "Batch",
                            ProductBrand = product.Brand.Name,
                            ProductCategory = product.Category.Name,
                            ProductName = product.Name,
                            ProductId = product.Id,
                            ProductPrice = product.Price,
                            ProductExpiry = product.Expiry,
                            ProductStatus = product.StockStat,
                            ProductStock = product.Stock,
                            BatchBase = batch.BasePrice,
                            BatchExpiry = batch.Expiry,
                            BatchId = batch.Id,
                            BatchStock = batch.Stock
                        };
                        _unitOfWork.InvReportDetail.Add(Bdetail);
                    };
                }
                DateTime today = DateTime.Now;
                Inventory.GenerationDate = new DateTime(today.Year, today.Month, today.Day, today.Hour, today.Minute, today.Second, today.Kind);
                _unitOfWork.InventoryReport.Update(Inventory);
                TempData["Success"] = "Report Generated Successfully";
            }

            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
        return View(Inventory);
    }

    //GET
    //public IActionResult Delete(int? id)
    //{
    //    if (id == null || id == 0)
    //    {
    //        return NotFound();
    //    }

    //    var productFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

    //    if (productFromDbFirst == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(productFromDbFirst);
    //}



    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var InventoryList = _unitOfWork.InventoryReport.GetAll();
        return Json(new { data = InventoryList });
    }

    public IActionResult GetAll2(int id)
    {
        IEnumerable<InvReportDetail> Products = _unitOfWork.InvReportDetail.GetAll(u => u.DetailType == "Product" && u.ReportId == id);
        return Json(new { data = Products });
    }
    public IActionResult GetAll3(int id, int pid)
    {
        IEnumerable<InvReportDetail> Batches = _unitOfWork.InvReportDetail.GetAll(u => u.DetailType == "Batch" && u.ProductId == pid && u.ReportId == id);
        return Json(new { data = Batches });
    }
    public IActionResult Excel(int id)
    {
        InventoryReport report = _unitOfWork.InventoryReport.GetFirstOrDefault(u => u.Id == id);
        IEnumerable<InvReportDetail> Products = _unitOfWork.InvReportDetail.GetAll(u => u.DetailType == "Product" && u.ReportId == id);

        ExcelPackage pack = new ExcelPackage();
        ExcelWorksheet ws = pack.Workbook.Worksheets.Add("Report");

        ws.Cells["A1"].Value = "Inventory Report";
        ws.Cells["B1"].Value = report.Name;
        ws.Cells["A2"].Value = "Report Generated";
        ws.Cells["B2"].Value = report.GenerationDate.ToString();
        ws.Cells["A3"].Value = "Excel Generated";
        var time = DateTime.Now;
        ws.Cells["B3"].Value = new DateTime(time.Year, time.Month, time.Day, time.Hour, time.Minute, time.Second, time.Kind).ToString();

PLMWebApp/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PLM.DataAccess;
using PLM.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting; 
using PLM.Models;
using PLM.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using PLM.Utility;

namespace PLMWebApp.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Operation + "," + SD.Role_Marketing)]
public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SeeAll()
        {
            return View();
        }

    //GET
    public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll(u=>u.IsActive).Select(i=>new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                BrandList = _unitOfWork.Brand.GetAll(u => u.IsActive).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };    

            if (id==null || id == 0)
            {
                //Create Product
                //ViewBag.CategoryList = CategoryList;
                //ViewData["BrandList"] = BrandList;
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                //Update Product
                return View(productVM);
            }
            
            
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);
                    
                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                        System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;
                }

                if (obj.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.Product);
                    TempData["Success"] = "Product Created Successfully";
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                    TempData["Success"] = "Product Updated Successfully";
                }

                _unitOfWork.Save();
                
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }

        //    var productFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

        //    if (productFromDbFirst == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productFromDbFirst);
        //}



    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Product.GetAll(u=>u.IsActive,includeProperties:"Category,Brand");
        return Json(new { data = productList });
    }
    public IActionResult GetAll2()
    {
        var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,Brand");
        return Json(new { data = productList });
    }

    //POST
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deactivating" });
        }

        //var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        //if (System.IO.File.Exists(oldImagePath))
        //{
        //    System.IO.File.Delete(oldImagePath);
        //}
        obj.IsActive = false;
        obj.Inactivity = DateTime.Now;
        _unitOfWork.Product.Update(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Product Deactivated Successfully" });
        //return RedirectToAction("Index");

    }

    public IActionResult Activate(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while Reactivating" });
        }

        //var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        //if (System.IO.File.Exists(oldImagePath))
        //{
        //    System.IO.File.Delete(oldImagePath);
        //}
        obj.IsActive = true;
        _unitOfWork.Product.Update(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Product Reactivated Successfully" });
        //return RedirectToAction("Index");

    }

    #endregion
}

PLMWebApp/Areas/Admin/Views/InventoryReport/Batches.cshtml
@model PLM.Models.InvReportDetail

@{
    ViewData["Title"] = "Product" + @Model.ProductName;
}

<div class="container p-3">
    <input asp-for="ProductName" hidden />
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Batches for @Model.ProductName</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="InventoryReport" asp-action="Products" asp-route-id="@Model.ReportId" class="btn btn-primary">
                Return
            </a>
        </div>
    </div>

    <br />

    <table id="tblData" class="table table-hover" style="width: 100%">
        <thead>
            <tr>
                <th>
                    Expiration Date
                </th>
                <th>
                    Base Price
                </th>
                <th>
                    Stock
                </th>
            </tr>
        </thead>
    </table>

</div>


@section Scripts{
    <script>
        var dataTable;

        $(document).ready(function() {
            loadDataTable();
        });

        function loadDataTable() {
            dataTable = $('#tblData').DataTable({

                "ajax": {
                    "url": "/Admin/InventoryReport/GetAll3?id=" + @Model.ReportId + "&pid=" + @Model.ProductId
                },
                "columns": [
                    { "data": "batchExpiry", "width": "15%" },
                    { "data": "batchBase", "width": "5%" },
                    { "data": "batchStock", "width": "20%" },
                ]
            });
        }
    </script>
}

PLMWebApp/Areas/Admin/Views/InventoryReport/Index.cshtml
@{
    ViewData["Title"] = "Inventory Reports";
}

<div class="container p-3">

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Inventory Reports</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="InventoryReport" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Generate Report
            </a>
        </div>
    </div>

    <br />

    <table id="tblData" class="table table-hover" style="width: 100%">
        <thead>
            <tr>
                <th>
                    Generation Date
                </th>
                <th>
                    Name
                </th>
                <th></th>
            </tr>
        </thead>
    </table>

</div>


@section Scripts{
    <script>
        var dataTable;

        $(document).ready(function() {
            loadDataTable();
        });

        function loadDataTable() {
            dataTable = $('#tblData').DataTable({

                "ajax": {
                    "url": "/Admin/InventoryReport/GetAll"
                },
                order: [[0, 'desc']],
                "columns": [
                    { "data": "generationDate", "width": "20%" },
                    { "data": "name", "width": "20%" },
                    {
                        "data": "id",
                        "render": function(data) {
                            return `
                                <div class="w-75 btn-group" role="group">
                                    <a href="/Admin/InventoryReport/Upsert?id=${data}" class="btn btn-info mx-2">
                                        <i class="bi bi-pencil-square"> </i> Edit
                                    </a>
                                    <a href="/Admin/InventoryReport/Products?id=${data}" class="btn btn-primary mx-2">
                                        <i class="bi bi-bag-check"> </i> Inventory
                                    </a>
                                    <a onclick="Excel('/Admin/InventoryReport/Excel?id=${data}')" class="btn btn-success mx-2">
                                        <i class="bi bi-file-spreadsheet"></i> Excel
                                    </a>
                                    <a onclick="Delete('/Admin/InventoryReport/Delete/${data}')" class="btn btn-warning mx-2">
                                        <i class="bi bi-trash"></i> Delete
                                    </a>
                                </div>
                                `
                        },
                        "width": "20%"
                    }
                ]

            });
        }

        function Delete(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "Reports are permanently deleted",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        success: function(data) {
                            if (data.success) {
                                dataTable.ajax.reload();
                                toastr.success(data.message);
                            }
                            else {
                                toastr.error(data.message);
                            }
                        }
                    })
                }
            })
        }
        function Excel(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "This will download an Excel sheet for this report",
                icon: 'info',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = url;
                }
            })
        }
    </script>
}

PLMWebApp/Areas/Admin/Views/InventoryReport/Products.cshtml
@model PLM.Models.InventoryReport

@{
    ViewData["Title"] = "Inventory Report " + @Model.Name;
}

<div class="container p-3">
    <input asp-for="Name" hidden />
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Products for Report @Model.Name</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="InventoryReport" asp-action="Index" class="btn btn-primary">
                Return
            </a>
        </div>
    </div>

    <br />

    <table id="tblData" class="table table-hover" style="width: 100%">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Stock
                </th>
                <th>
                    Status
                </th>
                <th>
                    Expiration
                </th>
                <th>
                    Price
                </th>
                <th>
                    Brand
                </th>
                <th>
                    Category
                </th>
                <th>

                </th>
            </tr>
        </thead>
    </table>

</div>


@section Scripts{
    <script>
        var dataTable;

        $(document).ready(function() {
            loadDataTable();
        });

        function loadDataTable() {
            dataTable = $('#tblData').DataTable({

                "ajax": {
                    "url": "/Admin/InventoryReport/GetAll2?id=" + @Model.Id
                },
                "columns": [
                    { "data": "productName", "width": "15%" },
                    { "data": "productStock", "width": "5%" },
                    { "data": "productStatus", "width": "20%" },
                    { "data": "productExpiry", "width": "15%" },
                    { "data": "productPrice", "width": "10%" },
                    { "data": "productBrand", "width": "10%" },
                    { "data": "productCategory", "width": "10%" },
                    {
                        "data": "id",
                        "render": function(data, type, row) {
                            return `
                            <div class="w-75 btn-group" role="group">
                                <a href="/Admin/InventoryReport/Batches?id=${row["reportId"]}&pid=${row["productId"]}" class="btn btn-info mx-2">
                                    <i class="bi bi-pencil-square"> </i> Batches
                                </a>
                            </div>
                            `
                        },
                        "width": "5%"
                    }
                ]
            });
        }
    </script>
}

PLMWebApp/Areas/Admin/Views/InventoryReport/Upsert.cshtml
@using PLM.Utility
@model PLM.Models.InventoryReport

@{
    ViewData["Title"] = "Inventory";
}

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input hidden asp-for="Id"/>
    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id != 0? "Update" : "Generate New") Inventory Report</h2>
                </div>
                <div class="mb-3">
                    @*<div asp-validation-summary="All"></div>*@
                    <label asp-for="Name"></label>
                    <br />
                    <input asp-for="Name" type="text" class="form-control" id="floatingInput" placeholder="Inventory Report Label">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
                    }
                    else
                    {
                        <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width: 150px">Generate</button>
                    }
                    <a asp-controller="InventoryReport" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back To List</a>
                </div>
            </div>
        </div>
    </div>
</form>