PLMWebApp/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PLM.DataAccess;
using PLM.DataAccess.Repository.IRepository;
using PLM.Models;
using PLM.Utility;

namespace PLMWebApp.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin +","+ SD.Role_Operation + "," + SD.Role_Marketing)]
public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Brand> objBrandList = _unitOfWork.Brand.GetAll(u=>u.IsActive);
            return View(objBrandList);
        }
        public IActionResult SeeAll()
        {
            IEnumerable<Brand> objBrandList = _unitOfWork.Brand.GetAll();
            return View(objBrandList);
        }

    //GET
    public IActionResult Create()
        {
            
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Brand obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Brand.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Brand Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id==null || id == 0)
            {
                return NotFound();
            }
            var brandFromDbFirst = _unitOfWork.Brand.GetFirstOrDefault(u => u.Id == id);

            if(brandFromDbFirst == null)
            {
                return NotFound();
            }

            return View(brandFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Brand obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Brand.Update(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Brand Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var brandFromDbFirst = _unitOfWork.Brand.GetFirstOrDefault(u => u.Id == id);

            if (brandFromDbFirst == null)
            {
                return NotFound();
            }

            return View(brandFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Brand.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            obj.IsActive = false;
            obj.Inactivity = DateTime.Now;
            _unitOfWork.Brand.Update(obj);
            _unitOfWork.Save();
            TempData["Success"] = "Brand Deleted Successfully";
            return RedirectToAction("Index");

        }

    public IActionResult Activate(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var BrandFromDbFirst = _unitOfWork.Brand.GetFirstOrDefault(u => u.Id == id);

        if (BrandFromDbFirst == null)
        {
            return NotFound();
        }

        return View(BrandFromDbFirst);
    }

    //POST
    [HttpPost, ActionName("Activate")]
    [ValidateAntiForgeryToken]
    public IActionResult ActivatePOST(int? id)
    {
        var obj = _unitOfWork.Brand.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }
        obj.IsActive = true;
        _unitOfWork.Brand.Update(obj);
        _unitOfWork.Save();
        TempData["Success"] = "Brand Activated Successfully";
        return RedirectToAction("SeeAll");
    }
}

PLMWebApp/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using PLM.DataAccess;
using PLM.DataAccess.Repository.IRepository;
using PLM.Models;
using Microsoft.AspNetCore.Authorization;
using PLM.Utility;

namespace PLMWebApp.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Operation + "," + SD.Role_Marketing)]
public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
        IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll(u=>u.IsActive);
        return View(objCategoryList);
        }

        public IActionResult SeeAll()
        {
        IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
        return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {
            
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id==null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

            if(categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            obj.IsActive = false;
            obj.Inactivity = DateTime.Now;
            _unitOfWork.Category.Update(obj);
            _unitOfWork.Save();
            TempData["Success"] = "Category Deactivated Successfully";
            return RedirectToAction("Index");

        }

        public IActionResult Activate(int? id)
        {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

        if (categoryFromDbFirst == null)
        {
            return NotFound();
        }

        return View(categoryFromDbFirst);
    }

    //POST
    [HttpPost, ActionName("Activate")]
    [ValidateAntiForgeryToken]
    public IActionResult ActivatePOST(int? id)
    {
        var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }
        obj.IsActive = true;
        _unitOfWork.Category.Update(obj);
        _unitOfWork.Save();
        TempData["Success"] = "Category Activated Successfully";
        return RedirectToAction("SeeAll");

    }
}

PLMWebApp/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PLM.DataAccess;
using PLM.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting; 
using PLM.Models;
using PLM.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using PLM.Utility;

namespace PLMWebApp.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Operation + "," + SD.Role_Marketing)]
public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SeeAll()
        {
            return View();
        }

    //GET
    public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll(u=>u.IsActive).Select(i=>new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                BrandList = _unitOfWork.Brand.GetAll(u => u.IsActive).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };    

            if (id==null || id == 0)
            {
                //Create Product
                //ViewBag.CategoryList = CategoryList;
                //ViewData["BrandList"] = BrandList;
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                //Update Product
                return View(productVM);
            }
            
            
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);
                    
                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                        System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;
                }

                if (obj.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.Product);
                    TempData["Success"] = "Product Created Successfully";
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                    TempData["Success"] = "Product Updated Successfully";
                }

                _unitOfWork.Save();
                
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }

        //    var productFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

        //    if (productFromDbFirst == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productFromDbFirst);
        //}



    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Product.GetAll(u=>u.IsActive,includeProperties:"Category,Brand");
        return Json(new { data = productList });
    }
    public IActionResult GetAll2()
    {
        var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,Brand");
        return Json(new { data = productList });
    }

    //POST
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deactivating" });
        }

        //var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        //if (System.IO.File.Exists(oldImagePath))
        //{
        //    System.IO.File.Delete(oldImagePath);
        //}
        obj.IsActive = false;
        obj.Inactivity = DateTime.Now;
        _unitOfWork.Product.Update(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Product Deactivated Successfully" });
        //return RedirectToAction("Index");

    }

    public IActionResult Activate(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while Reactivating" });
        }

        //var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        //if (System.IO.File.Exists(oldImagePath))
        //{
        //    System.IO.File.Delete(oldImagePath);
        //}
        obj.IsActive = true;
        _unitOfWork.Product.Update(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Product Reactivated Successfully" });
        //return RedirectToAction("Index");

    }

    #endregion
}

PLMWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PLM.Utility

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meatify </title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PLMWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <form id="logoutForm2" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
    </form>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <h2><a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Meatify</a></h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a>
                        </li>*@
                        <li class="nav-item">
                            @*<a class="nav-link" href="#">Pricing</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                            </li>*@
                            
                            <li class="nav-item dropdown">
                            @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Logistics) || User.IsInRole(SD.Role_Sales) || User.IsInRole(SD.Role_Operation) || User.IsInRole(SD.Role_Marketing))
                                {
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Management</a>
                                }
                                <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Inventory" asp-action="Index">Inventory</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Userlist" asp-action="Index">Account Manager</a>
                            @*@*<a class="dropdown-item" href="#">Something else here</a>*@
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Sales" asp-action="Index">Sales Reports</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="InventoryReport" asp-action="Index">Inventory Reports</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="ReservationReport" asp-action="Index">Reservation Reports</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Delivery" asp-action="Index">Delivery Reports</a>
                            @*<a class="dropdown-item" asp-area="Admin" asp-controller="Region" asp-action="Index">Region</a>
                            <a class="dropdown-item" href="#">Separated link</a>*@
                            </div>
                            
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Reservation" asp-action="Index">
                                Reservations
                            </a>
                        </li>   
                        @if (User.IsInRole(SD.Role_Admin))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" id="register" asp-area="Identity" asp-page="/Account/RegisterAdmin">Admin Register</a>
                                </li>
                            }
                        <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                            <i class="bi bi-cart"></i>
                        </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Type here...">
                        <button class="btn btn-outline-dark" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Meatify - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @*<script src="https://cdn.tiny.cloud/1/rrymswpjlf22esylw6vd7qvf7vg9jcmds6czc3ht8bwd23f3/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
    <script> 
        var idleTime = 0;
        $(document).ready(function () {
            //Increment the idle time counter every minute.
            var idleInterval = setInterval(timerIncrement, 60000); // 1min
            
            //Zero the idle timer on mouse movement.
            $(this).mousemove(function (e) {
                idleTime = 0;
            });
            $(this).keypress(function (e) {
                idleTime = 0;
            });
        });

        function timerIncrement() {
            idleTime = idleTime + 1;
            if (idleTime > @SD.MinuteTimeout) { // x minutes
                var signed = '@(SignInManager.IsSignedIn(User) ? "true" : "false")';
                var custom = '@(User.IsInRole(SD.Role_Customer) ? "true" : "false")';
                if (signed == "true" && custom == "false")
                { 
                    document.getElementById("logoutForm2").submit();
                }
            }
        }
        var signed = '@(SignInManager.IsSignedIn(User) ? "true" : "false")';
        var customer = '@(User.IsInRole(SD.Role_Customer) ? "true" : "false")';
        var area = window.location.href.includes("Account");
        if (signed == "true" && customer == "true" && !area) { 
            $.ajax({
				url: "/Customer/Home/Validate",
				type:'GET',
				success: function(result){
                    if (!result.success) {
                        window.location.href = "/Identity/Account/Manage";
                    }
				}
			})
        }

    </script>
</body>
</html>

PLMWebApp/Views/Shared/_Notification.cshtml
@if(TempData["Success"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}
@if(TempData["Error"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}